from database.connection import Database


class ProfileService:
    """
    Service responsible for saving data profiling
    results into the database.
    """

    @staticmethod
    def save(profiles):
        """
        Save profiling statistics into the data_profile table.

        Parameters
        ----------
        profiles : list
            List of dictionaries generated by DataProfiler.
            Each dictionary contains profiling statistics
            for one column.
        """

        # -----------------------------------------
        # Create database connection
        # -----------------------------------------
        db = Database()
        db.connect()

        # Create cursor to execute SQL queries
        cursor = db.connection.cursor()

        # -----------------------------------------
        # SQL INSERT query
        # -----------------------------------------
        query = """
        INSERT INTO data_profile
        (
            column_name,
            data_type,
            total_rows,
            null_count,
            null_percentage,
            unique_values,
            minimum_value,
            maximum_value,
            average_value
        )

        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """

        # -----------------------------------------
        # Insert profile for each column
        # -----------------------------------------
        for profile in profiles:

            cursor.execute(

                query,

                (
                    profile["column_name"],
                    profile["data_type"],
                    profile["total_rows"],
                    profile["null_count"],
                    profile["null_percentage"],
                    profile["unique_values"],
                    profile["min"],
                    profile["max"],
                    profile["mean"]
                )

            )

        # -----------------------------------------
        # Save changes permanently
        # -----------------------------------------
        db.connection.commit()

        # Close cursor
        cursor.close()

        # Disconnect database
        db.disconnect()